export const PLAYER_CONSTANTS = {
 SPEED_BASE: 20,
 SPEED_RUNNING: 30,

 JUMP_COOLDOWN_IN_TICKS: 50,
 JUMP_HORIZONTAL: 0,
 JUMP_VERTICAL: -2000,

 DELAY_BEFORE_CAN_DOUBLE_JUMP: 10,

 DOUBLE_JUMP_COOLDOWN_IN_TICKS: 50,
 DOUBLE_JUMP_HORIZONTAL: 0,
 DOUBLE_JUMP_VERTICAL: -2000,

 DASH_COOLDOWN_IN_TICKS: 120,
 DASH_HORIZONTAL: 2500,
 DASH_VERTICAL: -98
}
